apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dotnet-github-tekton-2511 
  janus-idp.io/tekton: dotnet-github-tekton-2511
  backstage.io/kubernetes-id: dotnet-github-tekton-2511
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet-github-tekton-2511
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  