apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dotnet-github-tekton-2511-gitops
  description: This is GitOps manifest for dotnet-github-tekton-2511   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: dotnet-github-tekton-2511
    backstage.io/kubernetes-id: dotnet-github-tekton-2511 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: dotnet-github-tekton-2511   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dotnet-github-tekton-2511
